spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  flyway:
    enabled: true
    schemas: user_settings
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 7000
management:
  port: 7001

logging:
  level:
    org:
      springframework:
        web: DEBUG