INSERT INTO ACCOUNT_SETTINGS (ID, ACCOUNT_NAME, ACCOUNT_ORDER)
VALUES ('1', 'ACCOUNT-1', 1);

INSERT INTO ACCOUNT_SETTINGS (ID, ACCOUNT_NAME, ACCOUNT_ORDER)
VALUES ('2', 'ACCOUNT-2', 2);

INSERT INTO ACCOUNT_SETTINGS (ID, ACCOUNT_NAME, ACCOUNT_ORDER)
VALUES ('3', 'ACCOUNT-3', 3);

INSERT INTO ACCOUNT_SETTINGS (ID, ACCOUNT_NAME, ACCOUNT_ORDER)
VALUES ('4', 'ACCOUNT-4', 4);

INSERT INTO ACCOUNT_SETTINGS (ID, ACCOUNT_NAME, ACCOUNT_ORDER)
VALUES ('5', 'ACCOUNT-5', 5);

INSERT INTO ACCOUNT_SETTINGS (ID, ACCOUNT_NAME, ACCOUNT_ORDER)
VALUES ('6', 'ACCOUNT-6', 6);

INSERT INTO ACCOUNT_SETTINGS (ID, ACCOUNT_NAME, ACCOUNT_ORDER)
VALUES ('7', 'ACCOUNT-7', 7);

INSERT INTO ACCOUNT_SETTINGS (ID, ACCOUNT_NAME, ACCOUNT_ORDER)
VALUES ('8', 'ACCOUNT-8', 8);

INSERT INTO ACCOUNT_SETTINGS (ID, ACCOUNT_NAME, ACCOUNT_ORDER)
VALUES ('9', 'ACCOUNT-9', 9);

INSERT INTO ACCOUNT_SETTINGS (ID, ACCOUNT_NAME, ACCOUNT_ORDER)
VALUES ('10', 'ACCOUNT-10', 10);
